% predefine parameters
config.SPMdir='C:\Program Files\MATLAB\spm12\'; % installed directory of spm: e.g. G:\guobin\spm12\
config.image_dir=fullfile(pwd, 'imgs');
config.group_t1_dir=fullfile(config.image_dir, '/T1/');
config.group_mra_dir=fullfile(config.image_dir, 'MRA/');
config.group_mrapred_dir=config.group_mra_dir;

config.newseg_jobmatfile=fullfile(pwd, 'jobmats/NewSegment.mat'); 
config.create_template_jobmatfile=fullfile(pwd, 'jobmats/Dartel_CreateTemplate.mat'); 
config.normalize_matfile=fullfile(pwd, 'jobmats/Dartel_NormaliseToMNI_ManySubjects.mat');
config.coreg_matfile=fullfile(pwd, 'jobmats/Coregister_Estimate_Reslice.mat');

% prefix of the subject folders
config.folder_prefix='Subj';
% prefix/suffix of corresponding T1 files
config.file_prefix='Subj';
config.file_suffix='.nii';
% sort the subject folders according to their names
% this is the folder ranked in the first
% wherein some critical files are saved
config.first_subj_folder='Subj0001'; 

% predicted files generated by our deep learning model will be renamed by
% adding a file suffix which could be modified in the corresponding .py
% file. This parameter should be modified accordingly.
config.predfile_suffix='_Pred.nii';

% threshold to binarize individual gray matter mask
config.gmthre=0.5;

% resliced all T1 files to resolution space of 0.5 * 0.5 * 0.5 mm3
config.resliced_voxel=[0.5 0.5 0.5];

% predefined atlas in MNI space
config.brodmann_atlas=fullfile(pwd, 'atlas/Brodmann_atlas.nii');
config.lobe_atlas=fullfile(pwd, 'atlas/Lobes_atlas.nii');
config.cow_atlas=fullfile(pwd, 'atlas/CoW_atlas.nii');

config.coregmra_prefix='coreg';
config.coregmrapred_prefix='ToT1';

config.combined_predictionfile='combined_prediction.nii';

save('config.mat', "config");